const SET_CARE = 'SET_CARE';
const SET_USER_DEPLACEMENTS = 'SET_USER_DEPLACEMENTS';
const SET_AUTHENTICATED = 'SET_AUTHENTICATED';



export{
    SET_CARE,
    SET_USER_DEPLACEMENTS,
    SET_AUTHENTICATED
}